### GET data throught proxy
GET http://localhost:3100/api/proxy/data/products

### GET cmsPages
GET http://localhost:3101/api/pages?pLevel
Authorization: Bearer {{cmsToken}}

### GET cmsPages throught proxy
GET http://localhost:3100/api/proxy/cms/api/pages?pLevel
Authorization: Bearer {{cmsToken}}

